# Generated by Django 3.1.2 on 2020-11-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcount',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
